[package]
name = "tracing-serde"
# TODO: Needs to be bumped
version = "0.1.3"
authors = ["Tokio Contributors <team@tokio.rs>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
description = """
A compatibility layer for serializing trace data with `serde`
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
    "encoding",
]
keywords = ["logging", "tracing", "serialization"]
rust-version = "1.51.0"

[features]
default = ["std"]
std = ["serde/std", "tracing-core/std"]
valuable = ["valuable_crate", "valuable-serde", "tracing-core/valuable"]

[dependencies]
serde = { version = "1", default-features = false, features = ["derive"] }
tracing-core = { path = "../tracing-core", version = "0.1.22", default-features = false}
heapless = { version = "0.7.10", features = ["serde"] }
hash32 = "0.2.1"

[dev-dependencies]
serde_json = "1"

# This is used for regression testing formatting between tracing-serde v0.2
# and tracing-serde v0.1
[dev-dependencies.tracing-serde-01]
package = "tracing-serde"
version = "=0.1.3"

[target.'cfg(tracing_unstable)'.dependencies]
valuable_crate = { package = "valuable", version = "0.1.0", optional = true, default_features = false }
valuable-serde = { version = "0.1.0", optional = true, default_features = false }

[badges]
maintenance = { status = "experimental" }

[patch.crates-io]
tracing-core = { path = "../../tracing-core" }
